CREATE TABLE company_user (
      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      login varchar(255) NOT NULL,

      CONSTRAINT company_user_pkey PRIMARY KEY (id),
      CONSTRAINT company_user_uniq_login UNIQUE (login)
);


CREATE TABLE patient_profile (
     id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     first_name varchar(255) NULL,
     last_name varchar(255) NULL,
     old_client_guid varchar(255) NULL,
     status_id integer NOT NULL,

     CONSTRAINT patient_profile_pkey PRIMARY KEY (id)
);


CREATE TABLE patient_note (
      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      old_note_guid varchar(255) NOT NULL,
      created_date_time timestamp NOT NULL,
      last_modified_date_time timestamp NOT NULL,
      created_by_user_id bigint NULL,
      last_modified_by_user_id bigint NULL,
      note varchar(4000) NULL,
      patient_id bigint NOT NULL,

      CONSTRAINT patient_note_pkey PRIMARY KEY (id)
);

INSERT INTO patient_profile (id, first_name, last_name, old_client_guid, status_id)
VALUES (1, 'Alex', 'Miranovich', '1', 200);

ALTER TABLE patient_note ADD CONSTRAINT fk_pat_note_to_modifyed_user FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user(id);
ALTER TABLE patient_note ADD CONSTRAINT fkpat_note_to_created_user FOREIGN KEY (created_by_user_id) REFERENCES company_user(id);
ALTER TABLE patient_note ADD CONSTRAINT fk_pat_note_to_patient FOREIGN KEY (patient_id) REFERENCES patient_profile(id);
